#Official Node.js image
FROM node:16

# Set working directory
WORKDIR /app

# Copy the .env.production file
COPY .env.production ./.env.production

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application files
COPY . .

# Expose the port the app runs on
EXPOSE 5000

# Start the app
CMD [ "npm", "start" ]