apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: movie-pilot-app-cert
  namespace: default
spec:
  commonName: movie-pilot-app.xyz
  dnsNames:
    - api.movie-pilot-app.xyz
    - www.movie-pilot-app.xyz
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  secretName: movie-pilot-app-tls
