apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: constantin21/backend:latest
          ports:
            - containerPort: 5000
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: JWT_SECRET
            - name: MONGO_DB_URI
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: MONGO_DB_URI
            - name: NODEMAILER_KEY
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: NODEMAILER_KEY
            - name: EMAIL_SENDER
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: EMAIL_SENDER
            - name: STRIPE_WEB_HOOK_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: STRIPE_WEB_HOOK_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
