name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push frontend Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend:latest -f Dockerfile .
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend:latest

      - name: Build and push backend Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/backend:latest -f backend/Dockerfile backend
          docker push ${{ secrets.DOCKER_USERNAME }}/backend:latest

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: "v1.21.0"

      - name: Configure Google Cloud CLI
        uses: google-github-actions/configure-gcloud@v0.3.0
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: third-mercury-426814-j4

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/frontend-deployment.yaml
          kubectl apply -f k8s/backend-deployment.yaml
          kubectl apply -f k8s/mongo-deployment.yaml
